### PR TITLE
D3 updates

### LINKED ISSUE #76: Prevent subgraphs in visualization from going out of view
Currently, the forces on our force graph are causing some unattached nodes to fly out of view. Is there a way to confine the nodes to the bounds of the graph area?

### PR DESCRIPTION
**Pull request by princiya**
This PR has some updates to `viz.js`
- Tries to solve #94. Although this issue wasn't a bug, graphs are improved in this PR
- thirdParties are blue in color
- hover state for text labels

This PR aimed to solve #76, but as per discussions, we have decided to implement it in #77.

### CODE REVIEW

**Comment by princiya** [comment]
screen shot 2017-07-10 at 22 46 49

**Comment by biancadanforth** [comment]
@princiya Tested this; still doesn't work. The `getX` and `getY` methods return the (x,y) coordinates (`width`, `height`) if the `d.x` exceeds `width` and `d.y` exceeds `height`, causing these nodes to collapse onto each other at (`width`, `height`).
Looking to see if there's a d3 solution -- or in general a way to know the bounding box dimensions  (and centroid) of each subgraph and adjust? Seems overly complicated...

**Comment by princiya** [comment]
@jonathanKingston I have added hover state for labels in this PR. This might help @biancadanforth debug during the capture phase :)

This doesn't solve #92, because the styling isn't complete.

**Comment by jonathanKingston** [comment]
Thanks @princiya!

**Pull request merged**
